### ISSUE TITLE
Create executive summary in lieu of section abstracts 

### ISSUE THREAD

**Issue by thoufer** [thoufer/WaterfowlStatusReport#4]
I was thinking that there might be some benefit to stripping the abstracts from them, and combining them to an executive summary (ES) at the front of the report.  This would also add some continuity across reports, as the AHM report has an ES rather than an abstract.

**Comment by JLD-FWS** [comment]
Agree with this suggestion to combine ducks, geese, and swans into 1 executive summary and remove abstracts (i.e., report all habitat condition info first, then a summary paragraph for each spp group [ducks, geese, swans]).
